# Generated by Django 2.2.4 on 2019-08-14 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=32)),
                ('status', models.CharField(choices=[('OPEN', 'open'), ('PAID', 'paid'), ('OVERDUE', 'overdue'), ('CANCELLED', 'cancelled')], default='OPEN', max_length=16)),
                ('due_date', models.DateField()),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtors.Debtor')),
            ],
        ),
    ]
